### ISSUE TITLE
Plans to update for new versions of Ecto?

### ISSUE THREAD

**Issue by drernie** [samsamai/ecto_immigrant#1]
This seems like a really useful tool.  Are there plans to maintain it?

`Failed to use "ecto" (version 3.4.5) because
  ecto_immigrant (version 0.1.0) requires ~> 2.1
  ecto_sql (version 3.4.5) requires ~> 3.4.3
  phoenix_ecto (version 4.1.0) requires ~> 3.0
  mix.lock specifies 3.4.5
`

**Comment by brunorafa** [comment]
+1

**Comment by samsamai** [comment]
Thanks to @thalesmg we are now updated to use ecto 3.5
