### ISSUE TITLE
Plans to make the data_migrations rollbackable?

### ISSUE THREAD

**Issue by aleDsz** [samsamai/ecto_immigrant#4]
Hi, we're using this library in our company and I tried to rollback a local `data_migration` but the function `down` doesn't exist. So, I was thinking about to contribute and implements this feature to be able to rollback like `mix ecto.rollback -n {number}`.

**Comment by samsamai** [comment]
Hi @aleDsz that sounds like a good addition, I didn't have any plans to do it, so if you want to work on it then that would be great.

**Comment by aleDsz** [comment]
@samsamai Perfect, so I'll do it and create a PR. Thanks for responding
